### ISSUE TITLE
Duplicate Reacts due to Lerna Monorepo? 

### ISSUE THREAD

**Issue by phoniks** [transmute-industries/material-did#18]
I'm running into the issue with hooks described [here](https://reactjs.org/warnings/invalid-hook-call-warning.html) - namely that React seems to be having trouble with my hooks, due to multiple versions of React being referenced.  I double checked that the first two causes are not at fault - it's not due to calling hooks out of place (I copied your pattern from the metamask demo to be sure), or mismatching versions of react and react-dom (see photo below)

![Screen Shot 2020-11-17 at 11 34 07 AM](https://user-images.githubusercontent.com/7213762/99438747-0dccdf80-28c9-11eb-8237-6c458d559eed.png)

I also ran the check suggested in the Duplicate React section of the [page](https://reactjs.org/warnings/invalid-hook-call-warning.html) to see if two different versions of React are being called, and it returned false (meaning there _are_ two different versions being called).  It seems like there are a few suggested solutions for this:

- [one involving Yarn resolutions](https://github.com/facebook/react/issues/13991#issuecomment-449597362), 
- [one involving npm-link-shared](https://github.com/facebook/react/issues/13991#issuecomment-435343455), and 
- [one involving a custom webpack config](https://github.com/facebook/react/issues/13991#issuecomment-435587809).  

I'm trying to lean away from the custom webpack config, since I started the project with CRA, and would prefer to avoid ejecting if possible.  I'm leaning towards the npm-link-shared solution, since it specifically mentions Lerna. Is there a tried and true solution to this issue?

**Comment by OR13** [comment]
The package structure for this repo is a bit hacky, we have been waiting for a TSDX mono repo template to refactor.

Seems almost ready to be tackled: 

https://github.com/formium/tsdx/pull/778

I'm not sure how to address your specific issue other than pointing to a working create react app example:

- https://github.com/transmute-industries/did-key.js/tree/master/packages/workbench
- https://github.com/OR13/didme.me

... I would recommend either copying one of those as a starting point, or using the yarn resolutions suggestion.

**Comment by gjgd** [comment]
Thanks for reporting! 

Can you provide steps to reproduce this issue? 

It is possible that it is related to `yarn` and the way it handles package resolution, which is different than `npm`
The lib should work regardless of which package manager people use, but we only tested it with `npm`. As temporary fix have you tried to install and run the project using `npm`?

**Comment by phoniks** [comment]
I'm using npm already.  I'm trying out the yarn resolution approach - if that doesn't work I'll see if I can provide steps to reproduce - or better yet, you can clone the repo [here](https://github.com/phoniks/transmute_tech_challenge).  But I don't think I've checked in these changes yet. At the moment homebrew update is hogging my CPU at the moment so as soon as that finishes I'll push them.

**Comment by phoniks** [comment]
Yep... looks like the yarn resolutions solution fixed it! Thanks for the help guys!
